"""Add user model

Revision ID: 3463e8c94a74
Revises: a9921c37b0b3
Create Date: 2026-09-30 22:48:58.767127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3463e8c94a74'
down_revision: Union[str, Sequence[str], None] = 'a9921c37b0b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM products")
    op.execute("DELETE FROM categories")
    op.execute("DELETE FROM users")
    op.add_column('categories', sa.Column('admin_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'admin_id')
    # ### end Alembic commands ###
