"""add order_id to order_items

Revision ID: 7352114c5caf
Revises: 755c776fa0c9
Create Date: 2026-10-07 17:40:35.702614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7352114c5caf'
down_revision: Union[str, Sequence[str], None] = '755c776fa0c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('order_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_order_items_user_id'), table_name='order_items')
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.drop_constraint(op.f('order_items_user_id_fkey'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_column('order_items', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_user_id_fkey'), 'order_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.create_index(op.f('ix_order_items_user_id'), 'order_items', ['user_id'], unique=False)
    op.drop_column('order_items', 'order_id')
    # ### end Alembic commands ###
